name: notes
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  notes_common:
    path: "../packages/notes_common"
  collection: ^1.16.0
  dio: ^4.0.6
  faker: ^2.0.0
  flutter_riverpod: ^2.0.2
  flutter_staggered_grid_view: ^0.6.2
  gap: ^2.0.0
  go_router: ^5.0.5
  riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
